# Generated by Django 4.2.2 on 2023-06-08 01:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroSecreto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_secreto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('id_numero_secreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogo.numerosecreto')),
            ],
        ),
    ]
