# Generated by Django 4.2.2 on 2023-06-08 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chute',
            old_name='id_numero_secreto',
            new_name='id_segredo',
        ),
        migrations.RenameField(
            model_name='numerosecreto',
            old_name='numero_secreto',
            new_name='segredo',
        ),
    ]
